"""empty message

Revision ID: 1dd00de86fc1
Revises: 
Create Date: 2023-04-23 16:37:23.700973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1dd00de86fc1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "np_chatgpt_plus_conversationid",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=256), nullable=False),
        sa.Column("conversation_id", sa.String(length=256), nullable=False),
        sa.Column("last_time", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("np_chatgpt_plus_conversationid")
    # ### end Alembic commands ###
