"""empty message

Revision ID: 1dd00de86fc2
Revises: 
Create Date: 2023-04-28 04:05:23.700973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1dd00de86fc2"
down_revision = "1dd00de86fc1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_user_id", "np_chatgpt_plus_conversationid", ["user_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_id", "np_chatgpt_plus_conversationid", type_="unique")
    # ### end Alembic commands ###
